export const ALL_PRODUCTS='ALL_PRODUCTS';
export const SET_ALL_PRODUCTS='SET_ALL_PRODUCTS';
export const CATEGORY_LIST='CATEGORY_LIST';
export const SET_CATEGORY_LIST='SET_CATEGORY_LIST';
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_TO_CART='REMOVE_TO_CART';